name: update_cron.
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # 1. 更新时区
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      # 2. 拉取分支
      - name: actions/checkout@master
        with: 
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # 3. 安装golang环境
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.3' # The Go version to download (if necessary) and use.

      # 4. 更新下载go mod
      - run: go mod download
      # 5. 运行 go
      - run: go run update_readme.go
      # 6. 提交 git
      - name: Commit file
        run: |
          git add README.md
          git config --local user.email "2291146413@qq.com"
          git config --local user.name "iuuuuuaena"
          git commit --allow-empty -m "Update news on $(date)" -a
      # 7. push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
